// Generated by CoffeeScript 1.7.1
(function() {
  var CommentUtility;

  CommentUtility = (function() {
    var DONE, IN_COMMENT, WAITING;

    WAITING = 0;

    IN_COMMENT = 1;

    DONE = 2;

    function CommentUtility() {
      this.lines = [];
      this.state = WAITING;
      this.commentLines = [];
    }

    CommentUtility.prototype.addLine = function(line) {
      line = this.cleanLine(line);
      switch (this.state) {
        case WAITING:
          if (this.isCommentBlockBegin(line)) {
            return this.state = IN_COMMENT;
          }
          break;
        case IN_COMMENT:
          if (this.isCommentBlockEnd(line)) {
            return this.state = DONE;
          } else {
            return this.commentLines.push(this.getCodeCommentPortion(line));
          }
          break;
        case DONE:
          return this.noop();
      }
    };

    CommentUtility.prototype.noop = function() {};

    CommentUtility.prototype.reset = function() {
      this.lines = [];
      this.state = WAITING;
      return this.commentLines = [];
    };

    CommentUtility.prototype.getCommentDoc = function() {
      return this.commentLines.join("\n");
    };

    CommentUtility.prototype.cleanLine = function(line) {
      line = line.trim();
      return line;
    };

    CommentUtility.prototype.getCodeCommentPortion = function(line) {
      if (line.indexOf("*") === 0) {
        return line.slice(line.indexOf("*"));
      }
      return line;
    };

    CommentUtility.prototype.isCommentBlockBegin = function(line) {
      return line.indexOf("###") === 0;
    };

    CommentUtility.prototype.isCommentBlockEnd = function(line) {
      return line.indexOf("###") === 0;
    };

    return CommentUtility;

  })();

  module.exports = CommentUtility;

}).call(this);
